### ISSUE TITLE
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_OFF'

### ISSUE THREAD

**Issue by saschachina** [syssi/xiaomi_fan#273]
After update to 2024.8.0.0 my fan became not available and i got following logs:

Logger: homeassistant
Quelle: custom_components/xiaomi_miio_airpurifier/fan.py:1268
Integration: xiaomi_miio_airpurifier ([Dokumentation](https://github.com/syssi/xiaomi_airpurifier), [Probleme](https://github.com/syssi/xiaomi_airpurifier/issues))
Erstmals aufgetreten: 18:21:07 (38 Vorkommnisse)
Zuletzt protokolliert: 18:39:37

```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1048, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1063, in __async_calculate_state
    capability_attr = self.capability_attributes
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 391, in capability_attributes
    supported_features = self.supported_features_compat
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 436, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miio_airpurifier/fan.py", line 1268, in supported_features
    | FanEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_OFF'
```

I double the check the IP address and the token, everything looks fine.

**Comment by syssi** [comment]
Which Home Assistant Core version do you use?

**Comment by saschachina** [comment]
> Which Home Assistant Core version do you use?

2024.7.4

**Comment by syssi** [comment]
2024.8.1 is required.

**Comment by syssi** [comment]
I missed enforcing this requirement using the manifest.

**Comment by saschachina** [comment]
> I missed enforcing this requirement using the manifest.

ok thanks for the information, then i will update to HA Core 2024.8.1

**Comment by syssi** [comment]
Please re-open the issue if it still doesn't work. :-)
