### ISSUE TITLE
Issue after update to 2022.04

### ISSUE THREAD

**Issue by Barma-lej** [syssi/xiaomi_fan#185]
Error integration after update to 2022.04
```
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error fan.xiaomi_miio_fan - cannot import name 'SPEED_OFF' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)
```
